apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Kubernetes resources to deploy
resources:
  - pvc.yaml
  - database.yaml
  - pv.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - grafana.yaml
  - prometheus.yaml
images:
  - name: bassemamri/ecoleback-app
    newTag: build-108
  - name: bassemamri/ecolefront-app
    newTag: build-105
